# Ejercicios: Getting & Knowing Your Data

### Objetivos de aprendizaje:
- Importar datos desde archivos y URLs
- Explorar la estructura básica de un DataFrame
- Usar métodos fundamentales: head(), tail(), shape, info(), describe()
- Entender tipos de datos y conversiones
- Realizar cálculos básicos sobre columnas

### Dataset: Chipotle Orders
Vamos a trabajar con datos de pedidos del restaurante Chipotle.

### Ejercicio 1: Importar las librerías necesarias
Importa pandas y numpy

In [2]:
# Pista: import pandas as pd, import numpy as np
import pandas as pd
import numpy as np

In [3]:
# Test: Verificar que pandas está importado
assert 'pd' in dir(), "Pandas no está importado como 'pd'"
print("✓ Test pasado: Librerías importadas correctamente")

✓ Test pasado: Librerías importadas correctamente

### Ejercicio 2: Cargar el dataset
Carga el dataset de Chipotle desde la URL proporcionada y asígnalo a una variable llamada `chipo`.

**URL:** https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv

In [4]:
# Pista: usa pd.read_csv() con el parámetro sep='\t' para archivos TSV
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url, sep='\t')

In [5]:
# Test: Verificar que el dataset se cargó correctamente
assert 'chipo' in dir(), "Variable 'chipo' no existe"
assert chipo.shape[0] > 0, "El DataFrame está vacío"
print(f"✓ Test pasado: Dataset cargado con {chipo.shape[0]} filas")

✓ Test pasado: Dataset cargado con 4622 filas

### Ejercicio 3: Visualizar las primeras 10 filas
Muestra las primeras 10 entradas del dataset

In [6]:
# Pista: usa el método .head() con un parámetro
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [7]:
# Test: No hay test automático para visualización
print("✓ Revisa visualmente que se muestran 10 filas")

✓ Revisa visualmente que se muestran 10 filas

### Ejercicio 4: Número de observaciones
¿Cuántas observaciones (filas) tiene el dataset?

In [8]:
# Pista: usa .shape[0] o len()
num_observaciones = chipo.shape[0]

In [9]:
# Test: Verificar el número de observaciones
assert num_observaciones == 4622, f"Esperado 4622, obtenido {num_observaciones}"
print(f"✓ Test pasado: {num_observaciones} observaciones")

✓ Test pasado: 4622 observaciones

### Ejercicio 5: Número de columnas
¿Cuántas columnas tiene el dataset?

In [10]:
# Pista: usa .shape[1] o len(chipo.columns)
num_columnas = chipo.shape[1]

In [11]:
# Test: Verificar el número de columnas
assert num_columnas == 5, f"Esperado 5, obtenido {num_columnas}"
print(f"✓ Test pasado: {num_columnas} columnas")

✓ Test pasado: 5 columnas

### Ejercicio 6: Nombres de las columnas
Imprime los nombres de todas las columnas

In [12]:
# Pista: usa el atributo .columns
nombres_columnas = chipo.columns
print(list(nombres_columnas))

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

In [13]:
# Test: Verificar nombres de columnas
columnas_esperadas = ['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']
assert list(chipo.columns) == columnas_esperadas, "Columnas incorrectas"
print("✓ Test pasado: Columnas correctas")

✓ Test pasado: Columnas correctas

### Ejercicio 7: Información del índice
¿Cómo está indexado el dataset?

In [14]:
# Pista: usa el atributo .index
chipo.index

RangeIndex(start=0, stop=4622, step=1)

In [15]:
# Test: Verificar que el índice es RangeIndex
assert isinstance(chipo.index, pd.RangeIndex), "Índice no es RangeIndex"
print("✓ Test pasado: Índice es RangeIndex (0, 1, 2, ...)")

✓ Test pasado: Índice es RangeIndex (0, 1, 2, ...)

### Ejercicio 8: Información general del DataFrame
Usa el método info() para ver información general sobre el dataset

In [16]:
# Pista: simplemente llama al método .info()
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [17]:
# Test: No hay test automático
print("✓ Revisa la información mostrada")

✓ Revisa la información mostrada

### Ejercicio 9: Tipos de datos
¿Qué tipo de dato tiene la columna 'item_price'?

In [18]:
# Pista: usa .dtype o .dtypes
tipo_price = chipo['item_price'].dtype
print(tipo_price)

str

In [20]:
# Test: Verificar tipo de dato
assert pd.api.types.is_string_dtype(chipo['item_price']), "El tipo debería ser texto (object/str)"
print(f"✓ Test pasado: item_price es de tipo {chipo['item_price'].dtype}")

✓ Test pasado: item_price es de tipo str

### Ejercicio 10: Total de items pedidos
¿Cuántos items fueron pedidos en total?

In [21]:
# Pista: suma la columna 'quantity'
total_items = chipo['quantity'].sum()

In [22]:
# Test: Verificar total
assert total_items == 4972, f"Esperado 4972, obtenido {total_items}"
print(f"✓ Test pasado: {total_items} items pedidos en total")

✓ Test pasado: 4972 items pedidos en total

### Ejercicio 11: Convertir precio a float
La columna 'item_price' es un string (object). Conviértela a float.

Primero, observa cómo están los valores (tienen el símbolo $ y espacios)

In [23]:
# Pista: Crea una función lambda que elimine el símbolo $ y convierta a float
# Usa .apply() para aplicarla a toda la columna
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x.replace('$', '').strip()))
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [24]:
# Test: Verificar conversión
assert chipo['item_price'].dtype in ['float64', 'float32'], f"Tipo incorrecto: {chipo['item_price'].dtype}"
print(f"✓ Test pasado: item_price convertido a {chipo['item_price'].dtype}")

✓ Test pasado: item_price convertido a float64

### Ejercicio 12: Revenue total
¿Cuál fue el ingreso total (revenue) del periodo?

In [25]:
# Pista: multiplica quantity * item_price y suma todo
revenue = (chipo['quantity'] * chipo['item_price']).sum()

In [26]:
# Test: Verificar revenue (aproximado)
assert 39000 < revenue < 40000, f"Revenue esperado ~39237, obtenido {revenue}"
print(f"✓ Test pasado: Revenue total = ${revenue:,.2f}")

✓ Test pasado: Revenue total = $39,237.02

### Ejercicio 13: Número de órdenes
¿Cuántas órdenes diferentes se realizaron?

In [27]:
# Pista: cuenta los valores únicos de 'order_id'
num_ordenes = chipo['order_id'].nunique()

In [28]:
# Test: Verificar número de órdenes
assert num_ordenes == 1834, f"Esperado 1834, obtenido {num_ordenes}"
print(f"✓ Test pasado: {num_ordenes} órdenes realizadas")

✓ Test pasado: 1834 órdenes realizadas

### Ejercicio 14: Revenue promedio por orden
¿Cuál es el ingreso promedio por orden?

In [29]:
# Pista: agrupa por order_id, suma el revenue de cada orden, y calcula el promedio
chipo['revenue'] = chipo['quantity'] * chipo['item_price']
revenue_promedio = chipo.groupby('order_id')['revenue'].sum().mean()

In [30]:
# Test: Verificar revenue promedio
assert 18 < revenue_promedio < 22, f"Revenue promedio esperado ~21, obtenido {revenue_promedio}"
print(f"✓ Test pasado: Revenue promedio por orden = ${revenue_promedio:.2f}")

✓ Test pasado: Revenue promedio por orden = $21.39

### Ejercicio 15: Items diferentes vendidos
¿Cuántos items diferentes se venden?

In [31]:
# Pista: cuenta los valores únicos de 'item_name'
items_unicos = chipo['item_name'].nunique()

In [32]:
# Test: Verificar items únicos
assert items_unicos == 50, f"Esperado 50, obtenido {items_unicos}"
print(f"✓ Test pasado: {items_unicos} items diferentes")

✓ Test pasado: 50 items diferentes

## ¡Ejercicios completados! 🎉

Has aprendido a:
- ✓ Cargar datos desde archivos y URLs
- ✓ Explorar la estructura de un DataFrame
- ✓ Trabajar con diferentes tipos de datos
- ✓ Realizar cálculos y agregaciones básicas