In [25]:
from scipy.io import arff
import pandas as pd
valores, metad = arff.loadarff("iris.arff")
df = pd.DataFrame(valores)

In [14]:
df

     sepallength  sepalwidth  petallength  petalwidth              class
0            5.1         3.5          1.4         0.2     b'Iris-setosa'
1            4.9         3.0          1.4         0.2     b'Iris-setosa'
2            4.7         3.2          1.3         0.2     b'Iris-setosa'
3            4.6         3.1          1.5         0.2     b'Iris-setosa'
4            5.0         3.6          1.4         0.2     b'Iris-setosa'
..           ...         ...          ...         ...                ...
145          6.7         3.0          5.2         2.3  b'Iris-virginica'
146          6.3         2.5          5.0         1.9  b'Iris-virginica'
147          6.5         3.0          5.2         2.0  b'Iris-virginica'
148          6.2         3.4          5.4         2.3  b'Iris-virginica'
149          5.9         3.0          5.1         1.8  b'Iris-virginica'

[150 rows x 5 columns]

In [21]:
df['class'] = df['class'].str.decode("utf-8")
df

     sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [23]:
import pandas as pd
df = pd.read_csv("Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [30]:
from scipy.io import arff
import pandas as pd
!wget https://raw.githubusercontent.com/Waikato/weka-3.8/master/wekadocs/data/iris.arff
valor, metad = arff.loadarff("iris.arff")
df = pd.DataFrame(valores)
df

"wget" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

     sepallength  sepalwidth  petallength  petalwidth              class
0            5.1         3.5          1.4         0.2     b'Iris-setosa'
1            4.9         3.0          1.4         0.2     b'Iris-setosa'
2            4.7         3.2          1.3         0.2     b'Iris-setosa'
3            4.6         3.1          1.5         0.2     b'Iris-setosa'
4            5.0         3.6          1.4         0.2     b'Iris-setosa'
..           ...         ...          ...         ...                ...
145          6.7         3.0          5.2         2.3  b'Iris-virginica'
146          6.3         2.5          5.0         1.9  b'Iris-virginica'
147          6.5         3.0          5.2         2.0  b'Iris-virginica'
148          6.2         3.4          5.4         2.3  b'Iris-virginica'
149          5.9         3.0          5.1         1.8  b'Iris-virginica'

[150 rows x 5 columns]

In [1]:
import pandas as pd
!wget https://archive.ics.uci.edu/static/public/53/iris.zip
!unzip iris.zip
df = pd.read_csv("iris.data",
names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
)
df

"wget" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"unzip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

FileNotFoundError: [Errno 2] No such file or directory: 'iris.data'

In [5]:
!wget "https://storage.googleapis.com/kaggle-data-sets/19/420/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20261021%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20261021T172704Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=4822be376165aa5a28f0ada8155b195011d55a5b5e3d7fcba02eeaf6f1c0f7a6ee3e05a2a877a0e1811c2c71f045862e2af477f7a0a58985d34513ee59c76750a4e8704de6f4067c918f6df71e972e2c222893362f2cd5528e2cc94ebdeb5b2efdf52b4b2910e796e60d4e709f05572d13ece8f38712674a2e1235278a72f77ba801db4963c5738998d87e558f48d28bb8f15fb63d7ad572379727281b2ae567e31c5b0f8cc6b9e53cc6aeabffb2cf3c09a6e8b68c2e81b5a3eefe0a18b4237dea5136eee0cafa53fd55eb1630d1e7776ded13f635984cc8320a972adaee6fe6d8b55378e1d7d4045a44a8383e110a75f18b29ada3f4609b1e951df938d19d7d" -O archive.zip
!unzip archive.zip
df = pd.read_csv("Iris.csv")
df

"wget" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"unzip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
df_values = pd.read_csv("https://raw.githubusercontent.com/LeadingIndiaAI/Heart-Disease-Prediction-Using-Machine-Learning-Techniques/master/train_values.csv") 
df_labels = pd.read_csv("https://raw.githubusercontent.com/LeadingIndiaAI/Heart-Disease-Prediction-Using-Machine-Learning-Techniques/master/train_labels.csv")
df = pd.merge(df_values, df_labels, on="patient_id")
df.drop(["patient_id"],axis=1, inplace=True)
df

,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina,heart_disease_present
0,1,normal,128,2,0,0,2,308,0.0,1,45,170,0,0
1,2,normal,110,3,0,0,0,214,1.6,0,54,158,0,0
2,1,normal,125,4,3,0,2,304,0.0,1,77,162,1,1
3,1,reversible_defect,152,4,0,0,0,223,0.0,1,40,181,0,1
4,3,reversible_defect,178,1,0,0,2,270,4.2,1,59,145,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2,reversible_defect,125,4,2,1,0,254,0.2,1,67,163,0,1
176,2,normal,180,4,0,0,1,327,3.4,0,55,117,1,1
177,2,reversible_defect,125,3,0,0,0,309,1.8,1,64,131,1,1
178,1,normal,124,3,2,1,0,255,0.0,1,48,175,0,0
179,1,normal,160,3,1,0,0,201,0.0,0,54,163,0,0

In [11]:
import pandas as pd
#!gdown 1mgpRXJFSMLmhC8359z5_Ev3Y4fv5404v
!gdown 1LbZwehJiBWLNOOGul36f2tBw3Xf8LtiU
df = pd.read_csv("Iris.csv")
df

"gdown" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica