In [25]:
from scipy.io import arff
import pandas as pd
valores, metad = arff.loadarff("iris.arff")
df = pd.DataFrame(valores)

In [14]:
df

     sepallength  sepalwidth  petallength  petalwidth              class
0            5.1         3.5          1.4         0.2     b'Iris-setosa'
1            4.9         3.0          1.4         0.2     b'Iris-setosa'
2            4.7         3.2          1.3         0.2     b'Iris-setosa'
3            4.6         3.1          1.5         0.2     b'Iris-setosa'
4            5.0         3.6          1.4         0.2     b'Iris-setosa'
..           ...         ...          ...         ...                ...
145          6.7         3.0          5.2         2.3  b'Iris-virginica'
146          6.3         2.5          5.0         1.9  b'Iris-virginica'
147          6.5         3.0          5.2         2.0  b'Iris-virginica'
148          6.2         3.4          5.4         2.3  b'Iris-virginica'
149          5.9         3.0          5.1         1.8  b'Iris-virginica'

[150 rows x 5 columns]

In [21]:
df['class'] = df['class'].str.decode("utf-8")
df

     sepallength  sepalwidth  petallength  petalwidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [23]:
import pandas as pd
df = pd.read_csv("Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [30]:
from scipy.io import arff
import pandas as pd
!wget https://raw.githubusercontent.com/Waikato/weka-3.8/master/wekadocs/data/iris.arff
valor, metad = arff.loadarff("iris.arff")
df = pd.DataFrame(valores)
df

"wget" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

     sepallength  sepalwidth  petallength  petalwidth              class
0            5.1         3.5          1.4         0.2     b'Iris-setosa'
1            4.9         3.0          1.4         0.2     b'Iris-setosa'
2            4.7         3.2          1.3         0.2     b'Iris-setosa'
3            4.6         3.1          1.5         0.2     b'Iris-setosa'
4            5.0         3.6          1.4         0.2     b'Iris-setosa'
..           ...         ...          ...         ...                ...
145          6.7         3.0          5.2         2.3  b'Iris-virginica'
146          6.3         2.5          5.0         1.9  b'Iris-virginica'
147          6.5         3.0          5.2         2.0  b'Iris-virginica'
148          6.2         3.4          5.4         2.3  b'Iris-virginica'
149          5.9         3.0          5.1         1.8  b'Iris-virginica'

[150 rows x 5 columns]

In [1]:
import pandas as pd
!wget https://archive.ics.uci.edu/static/public/53/iris.zip
!unzip iris.zip
df = pd.read_csv("iris.data",
names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
)
df

"wget" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"unzip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

FileNotFoundError: [Errno 2] No such file or directory: 'iris.data'

In [5]:
!wget "https://storage.googleapis.com/kaggle-data-sets/19/420/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20261021%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20261021T172704Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=4822be376165aa5a28f0ada8155b195011d55a5b5e3d7fcba02eeaf6f1c0f7a6ee3e05a2a877a0e1811c2c71f045862e2af477f7a0a58985d34513ee59c76750a4e8704de6f4067c918f6df71e972e2c222893362f2cd5528e2cc94ebdeb5b2efdf52b4b2910e796e60d4e709f05572d13ece8f38712674a2e1235278a72f77ba801db4963c5738998d87e558f48d28bb8f15fb63d7ad572379727281b2ae567e31c5b0f8cc6b9e53cc6aeabffb2cf3c09a6e8b68c2e81b5a3eefe0a18b4237dea5136eee0cafa53fd55eb1630d1e7776ded13f635984cc8320a972adaee6fe6d8b55378e1d7d4045a44a8383e110a75f18b29ada3f4609b1e951df938d19d7d" -O archive.zip
!unzip archive.zip
df = pd.read_csv("Iris.csv")
df

"wget" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"unzip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
df_values = pd.read_csv("https://raw.githubusercontent.com/LeadingIndiaAI/Heart-Disease-Prediction-Using-Machine-Learning-Techniques/master/train_values.csv") 
df_labels = pd.read_csv("https://raw.githubusercontent.com/LeadingIndiaAI/Heart-Disease-Prediction-Using-Machine-Learning-Techniques/master/train_labels.csv")
df = pd.merge(df_values, df_labels, on="patient_id")
df.drop(["patient_id"],axis=1, inplace=True)
df

,slope_of_peak_exercise_st_segment,thal,resting_blood_pressure,chest_pain_type,num_major_vessels,fasting_blood_sugar_gt_120_mg_per_dl,resting_ekg_results,serum_cholesterol_mg_per_dl,oldpeak_eq_st_depression,sex,age,max_heart_rate_achieved,exercise_induced_angina,heart_disease_present
0,1,normal,128,2,0,0,2,308,0.0,1,45,170,0,0
1,2,normal,110,3,0,0,0,214,1.6,0,54,158,0,0
2,1,normal,125,4,3,0,2,304,0.0,1,77,162,1,1
3,1,reversible_defect,152,4,0,0,0,223,0.0,1,40,181,0,1
4,3,reversible_defect,178,1,0,0,2,270,4.2,1,59,145,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2,reversible_defect,125,4,2,1,0,254,0.2,1,67,163,0,1
176,2,normal,180,4,0,0,1,327,3.4,0,55,117,1,1
177,2,reversible_defect,125,3,0,0,0,309,1.8,1,64,131,1,1
178,1,normal,124,3,2,1,0,255,0.0,1,48,175,0,0
179,1,normal,160,3,1,0,0,201,0.0,0,54,163,0,0

In [11]:
import pandas as pd
#!gdown 1mgpRXJFSMLmhC8359z5_Ev3Y4fv5404v
!gdown 1LbZwehJiBWLNOOGul36f2tBw3Xf8LtiU
df = pd.read_csv("Iris.csv")
df

"gdown" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
import pandas as pd
!wget file:///C:/Users/ia/Desktop/IABD/SAA/UD2/heart+disease.zip
! unzip heart+disease.zip
df = pd.read_csv('./heart+disease/processed.cleveland.data',
                 names=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num']
)
df

"wget" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"unzip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        303 non-null    str
 12  thal      303 non-null    str
 13  num       303 non-null    int64
dtypes: float64(11), int64(1), str(2)
memory usage: 33.3 KB

In [9]:
df[pd.to_numeric(df.ca,errors="coerce").isna() | pd.to_numeric(df.thal, errors="coerce").isna()]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
87,53.0,0.0,3.0,128.0,216.0,0.0,2.0,115.0,0.0,0.0,1.0,0.0,?,0
166,52.0,1.0,3.0,138.0,223.0,0.0,0.0,169.0,0.0,0.0,1.0,?,3.0,0
192,43.0,1.0,4.0,132.0,247.0,1.0,2.0,143.0,1.0,0.1,2.0,?,7.0,1
266,52.0,1.0,4.0,128.0,204.0,1.0,0.0,156.0,1.0,1.0,2.0,0.0,?,2
287,58.0,1.0,2.0,125.0,220.0,0.0,0.0,144.0,0.0,0.4,2.0,?,7.0,0
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [10]:
df.ca = pd.to_numeric(df.ca, errors='coerce')
df.thal = pd.to_numeric(df.thal, errors='coerce')

In [4]:
!unzip -o auto+mpg.zip -d auto+mpg

df = pd.read_csv(
    './auto+mpg/auto-mpg.data',
    names=['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
           'acceleration', 'model year', 'origin', 'car name'],
    sep=r'\s+',
    na_values='?'
)

df.head()

"unzip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

df.horsepower = pd.to_numeric(df.horsepower, errors='coerce')
df ['horsepower']=df['horsepower'].fillna (df['horsepower'].mean())

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    str
dtypes: float64(5), int64(3), str(1)
memory usage: 28.1 KB

In [7]:
df['num'].value_counts().sort_index().plot(kind='bar')

KeyError: 'num'